### ISSUE TITLE
Is it possible to know if one of the children of a menu item is active ?

### ISSUE THREAD

**Issue by k3z** [inveniosoftware/flask-menu#25]
Hello,

I have a two level navigation, the second level is collapsed, Is there a possibility to know if one of the children is active in the parent item ?

```
menu 1
menu 2 (active, if one of the children is active)
    child 1
    child 2 (active)
```

Thank you for your help.

**Comment by harobed** [comment]
+1

**Comment by jirikuncar** [comment]
We could change the default condition in https://github.com/inveniosoftware/flask-menu/blob/master/flask_menu/__init__.py#L69

```python
self._active_when = lambda: request.endpoint == self._endpoint or any(
    child.active for child in itervalues(self._children)
)
```

or 

`active` property definition in https://github.com/inveniosoftware/flask-menu/blob/master/flask_menu/__init__.py#L200-L203
```python
    @property
    def active(self):
        """Return True if the menu item is active."""
        return self._active_when() or any(
            child.active for child in itervalues(self._children)
        )
```

PS: I'm for 1st solution. 
--
cc @lnielsen

**Comment by jirikuncar** [comment]
Alternatively we could add new property/method `has_active_child(self[, recursive=True])`. WDYT?

**Comment by k3z** [comment]
Thanks for the answers.
I prefer the last solution, has_active_child(…), it's more flexible, and dont break existing implementations.

**Comment by tiborsimko** [comment]
> Alternatively we could add new property/method has_active_child(self[, recursive=True]). WDYT?

:+1:
