### ISSUE TITLE
Some doubts about usage

### ISSUE THREAD

**Issue by fmerges** [inveniosoftware/flask-menu#31]
Hello,

I have several questions regarding using Flask-Breadcrumbs and Flask-Menu.

Following the example of Flask-Breadcrumbs I get as the first menu entry a 'Menu item not initialised'.

Then is there a way to define the menu hierarchy not based on the endpoint? because for instance I have a view with a path argument in order to catch with it a multitude of pages-subpages, so currently I'm using the dynamic_list_constructor option, but that doesn't register the menu entries so that later I can say: this view is going to be at 'grandparent.parent.here', because that would not be initialised...

Thanks,

**Comment by fmerges** [comment]
Solved the first issue by adding:

breadcrumbs.default_breadcrumb_root(bp, '.')

I don't have a route (/) on the app, everything is in blueprints.

**Comment by fmerges** [comment]
Another question is why a dynamic_list_constructor gets called so many times?

**Comment by jirikuncar** [comment]
> Solved the first issue by adding:
> 
> `breadcrumbs.default_breadcrumb_root(bp, '.')`

Great :) Do you think you could provide full example for our documentation?

> Another question is why a dynamic_list_constructor gets called so many times?

Hmm, maybe we haven't thought about all cases. Can you add a test case and I will try to investigate it. Thanks!

**Comment by pournejati** [comment]
Hi, Can you provide an example on how to use "visible_when" option? I defined a function to return true or false and assigned it to this property, but it seems it doesn't function. Look at the following code:
```python
def has_role(role_id):
    return False

@menu.register_menu(app, '.providers', 'Provider Report', order=0, visible_when=has_role(1))
def list_providers():
    # ....
```

**Comment by fmerges** [comment]
Saeid,

You should not assign the return value of the function call to
visible_when, it should be a callable.

Cheers,

**Comment by jirikuncar** [comment]
In your case you need a function that returns a function (*function factory*).

**Example:**
```python
from flask_login import current_user

def has_role(role_id):
    def decider():
        return role_id in current_user['roles']
    return decider

@menu.register_menu(app, '.providers', 'Provider Report', order=0, visible_when=has_role(1))
def list_providers():
    # ....
```

**Comment by rysev-a** [comment]
Hello, 
i can't understand how to use dynamic_list_constructor

i can do this

    @app.route('/first')
    @menu.register_menu(app, '.first', 'First', order=0)
    def first():
        return render_template('menu.html')

how i can to generate menu from list? for example i have list of pages
how i can do something as
    @app.route("/content/<page_name>")
    def a_page(page_name):
    ...

or i must wright
    @app.route('/<some page url>')
    @menu.register_menu(app, '.<some page>', '<some page text>', order=0)
    def first():
        return render_template('menu.html')
for every pages?

**Comment by jirikuncar** [comment]
You can have a look at http://flask-breadcrumbs.readthedocs.org/en/latest/#variable-rules.

```python
from flask import request, render_template

from .models import Page

def pages(*args, **kwargs):
    return [{'text': page.name, 'url': page.url}
            for page in Pages.query.all()]

@app.route("/content/<page_name>")
@menu.register_menu(app, '.<some page>', '',
                                 dynamic_list_constructor=pages)
def a_page(page_name):
    page = Page.query.filter_by(name=page_name).one_or_404()
    return render_template('page.html', page=page)
```

**Comment by rysev-a** [comment]
Sorry, can you explain what is '.<some page>', in code above?

In my example this is name of page. 

for "contacts" page:

```python
@app.route('/contacts)
@menu.register_menu(app, '.contacts', 'Contacts', order=0)
def contacts():
    return render_template('menu.html')
```
for "about: page:

```python
@app.route('/about)
@menu.register_menu(app, '.about', 'About', order=1)
def about():
    return render_template('menu.html')
```
and for many other page


I try use your solution

```python

def pages(*args, **kwargs):
    return [{'text': page.name, 'url': page.url}
            for page in Page.query.all()]

@app.route("/content/<page_name>")
@menu.register_menu(app, '<.some_page>', '',
                    dynamic_list_constructor=pages)
def a_page(page_name):
    page = Page.query.filter_by(name=page_name)
    return render_template('page.html', page=page)
```
this return werkzeug.routing.BuildError

How i can do something very simple, like this

```python
def pages(*args, **kwargs):
    return [{'text' : 'info',     'url' : 'info'},
            {'text' : 'about',    'url' : 'about'},
            {'text' : 'contacts', 'url' : 'contacts'}
           ]

@app.route("/")
@menu.register_menu(app, '.', 'Home', dynamic_list_constructor=pages)
def pages():
    return render_template('menu.html')
```

and my standart jinja template
```html
<ul>
  {%- for item in current_menu.children recursive -%}
  <li>
    <a href="{{ item.url}}" 
      {% if item.active%}
        class="active"
      {%- endif -%}
    >{{ item.text }}</a>
    {%- if item.children -%}
    <ul>
      {{ loop(item.children) }}
    </ul>
    {%- endif -%}
  </li>
  {%- endfor -%}
</ul>
```

**Comment by jirikuncar** [comment]
I will push new version that will improve the behavior. Right now you would need to update the template:

```jinja2
<ul>
  {%- for dynamic_items in current_menu.children recursive -%}
  {% for item in dynamic_items %}
  <li>
    <a href="{{ item.url}}" 
      {% if item.active%}
        class="active"
      {%- endif -%}
    >{{ item.text }}</a>
    {%- if item.children -%}
    <ul>
      {{ loop(item.children) }}
    </ul>
    {%- endif -%}
  </li>
  {%- endfor -%}
  {%- endfor -%}
</ul>
```
and `pages` to generate `MenuEntryMixin`s.
```python
def pages(*args, **kwargs):
    return [MenuEntryMixin(...), ...]
```

This is not ideal hence I'm going to improve it. It will probably break backward compatibility with `dynamic_list` method, but I can consider that it has never been properly documented and tested so I can do that, can't I?

**Comment by fmerges** [comment]
I was actually right now writing about this... there should be a clean interface to register stuff to the menu hierarchy, because currently there isn't... with the dynamic example you are not registering so the API functions to traverse doesn't work with it.

Another example is, say you have an action with a variable path and you have a concrete action for a specific path which happens to be inside of that hierarchy you end up with not initialized menu entries, because the dynamic generator hasn't been called, and your menu hierarchy is not established. In that case you have to add .register_menu calls to the variable path action view to register the parents of the concrete one. Rough example:
```python
  @bp.route('/<path:path>')
  @menu.register_menu(... dynamic_list_constructor=...)
  def page(path):
      pass

  @bp.route('/a/b/c')
  @menu.register_menu(...)
  def c():
      pass
```
In this case you have to add via decorators the call to register menu so that the parents for c are registered:
```python
  @bp.route('/<path:path>')
  @menu.register_menu(... dynamic_list_constructor=...)
  @menu.register_menu(...)
  @menu.register_menu(...)
  def page(path):
      pass
```
A scenario I see you may want to register your hierarchy beforehand is with the use of Flask-Flatpages...

In my case I ended up writing my own simple solution.

**Comment by rysev-a** [comment]
Oh, I can't use this. I beginner in python, but I can use flask, flask-login, flask-admin, sqlalchemy. 
Flask-menu is too dificult. In any case it is just html menu with some classes inside tags (active, hidden). 
I try to use it, because i wan't do my application in right way. I disappointed

**Comment by jirikuncar** [comment]
@rysev-a thank you for your feedback. We are working on improving documentation and making dynamic menu usage easier. It would be very helpful if you could describe your difficulties in more details.

Happy hacking!
