### ISSUE TITLE
Manually register menu

### ISSUE THREAD

**Issue by stevezau** [inveniosoftware/flask-menu#35]
Hi,

I am building an angularjs app which will sit on top of flask.

I'd like to use Flask-App to build the menu but alot of the pages don't have flask routes so my question is it possible to register a menu item without the decorator??

**Comment by jirikuncar** [comment]
Hi, it's possible you can register your menu items `before_first_request` (`before_first_app_request`).

--
See an example https://github.com/zenodo/zenodo/blob/master/zenodo/base/views.py#L53-L140

**Comment by paviro** [comment]
The example is no longer available, how is this possible?

**Comment by jacquerie** [comment]
> The example is no longer available, how is this possible?

Because that is a link that always points to the current master, which might have changed in the meantime. Here's a permanent link to some code that might help you: https://github.com/inspirehep/inspire-next/blob/3e4cebee313ce2fff0c831ab99a2577868223861/inspirehep/modules/theme/views.py#L550-L565.

**Comment by paviro** [comment]
Just found it too but thank you anyway! :)
Adding an example snippet in case someone else needs it as well:
```
def add_menu_items():
	item = current_menu.submenu(".main.test")
	item._text = "Test"
	item._order = 1
	
app.before_first_request_funcs.append(add_menu_items)
```

**Comment by paviro** [comment]
I am still having a small problem...
I am adding a new menu by using the following code which works perfectly:
```
kitchen = current_menu.submenu("kitchen")
	kitchen._text = "K&uuml;che"
	kitchen._external_url = ""
	kitchen._order = 0
```

As a child of that menu item I have the following route:
```
@home.route("/rezepte")
@register_menu(home, 'kitchen.rezepte', 'Rezepte', order=0)
def rezepte():
	return render_template('rezepte.tpl', rezepte = rezepte.all())
```

My template looks something like this:
```
{%- for item in current_menu.children recursive -%}
  {% if item.children %}
    {{ item.text }} {% if item.active %}active{% endif %}
    {%- for child in item.children -%}
    {{ child.text }} {% if child.active %}active{% endif %}
    {%- endfor -%}
  {% else %}
   {{ item.text }} {% if item.active %}active{% endif %}
  {% endif %}
{%- endfor -%}
```

The child element (`child.active`) gets the `active` css class correctly but the manually created parent (`item.active`) does not.  I had a look at the `_active_when` method and it appears like this only works if the menu item has an actual endpoint which mine does not have, they are just groups for the other pages. 

Menu structure:
```
Group 1 (with no actual target)
---- Actual existing route 1
---- Actual existing route 2
Group 2 (with no actual target)
---- Actual existing route 3
---- Actual existing route 4
```

Is there any way to get the`item.active` variable set to `True` if the user is on one of the child-routes?

**Comment by paviro** [comment]
Any chance this is possible?

**Comment by jirikuncar** [comment]
@paviro you can try `item.has_active_child()` method.

**Comment by paviro** [comment]
That what I was searching for! Thank you so much! :)
