### ISSUE TITLE
Multiple routes can appear active at the same time

### ISSUE THREAD

**Issue by mordae** [inveniosoftware/flask-menu#58]
When I navigate to the longer of the following two routes, both are considered active:

    /test/hello
    /test/hello-and-bye

Is this by design or mistake?

**Comment by jirikuncar** [comment]
It's a default behavior (see https://github.com/inveniosoftware/flask-menu/blob/master/flask_menu/__init__.py#L89-L95). You can provide custom `active_when` method that compares only endpoint names.
